project:
  name: java
spring:
  profiles:
    active: dev
datasource:
  paike:
    jdbc-url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybaits:
  paike:
    config:
      location: classpath:mybatis/sqlmap_config.xml
      basepackage: com.dugu.java.dao.java